# -*- coding: utf-8 -*-
"""Patterns_Plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HonCX87PfH17CPOGQ7ld9Hj-mH31wG2v
"""

# General Libraries
import os
import re
from tqdm import tqdm
import pandas as pd
import numpy as np
# For the Visuals
import seaborn as sns
import matplotlib as mpl
from matplotlib import cm
import matplotlib.patches as patches
import matplotlib.pyplot as plt

#This lines of code is used to mount the google drive to colab
from google.colab import drive
drive.mount('/content/drive')

# Define a function to plot the sensors data using sensors data
def get_acc_lineplot(path, verbose=True):
    ex = pd.read_csv(path)
    ex = ex.melt(id_vars=["t"],
                value_vars=["F1", "F2"],
                var_name="FORCE_DATA")
    experiment_name = path.split("/")[-1].split(".")[0]

    # Plot
    plt.figure(figsize=(36, 12))
    plt.title(f"[{experiment_name}]", weight="bold", size=25)
    sns.lineplot(data=ex, x="t", y="value", hue="FORCE_DATA",
                 lw=2)
    plt.xlabel("Time", size = 18, weight="bold")
    plt.ylabel("Force(N)", size = 18, weight="bold")
    sns.despine(right=True, top=True, left=True)

#Define a path for the data
path1 = "/content/drive/MyDrive/BMEN 6367/SENSOR_DATA_new_modified"
#generate plots and dataframe from the data
for root, dirs, files in os.walk(path1):
        for name in tqdm(files):
            f_new = os.path.join(root, name)
            query_data_new = pd.read_csv(f_new)
            get_acc_lineplot(path=f_new)

# Travers all the branch of a specified path
for (root,dirs,files) in os.walk(path1,topdown=True):
  print("Directory path: %s"%root)
  print("Directory Names: %s"%dirs)
  print("Files Names: %s"%files)